# Sample .travis.yml for R projects

language: r
r: 
    - bioc-release
# warnings_are_errors: true
sudo: false
cache: packages

r_packages:
      - covr

os:
  - linux
  - osx

bioc_required: true
bioc_packages:
  - BiocCheck
  - BiocParallel
  - reactome.db

after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"

after_success:
      - Rscript -e 'covr::codecov()'
